GET  http://localhost:3001 

###
GET  http://localhost:3001/todo 

###
POST http://localhost:3001/new 
Content-Type: application/json

{
    "description":"Test from Client Rest"
}

###
DELETE http://localhost:3001/delete/3 HTTP/1.1